### ISSUE TITLE
Can this be implemented with SwiftUI?

### ISSUE THREAD

**Issue by Juhnkerg** [andrei-blaj/appstoreclone#2]
Can this be implemented with SwiftUI?  I tried for a long time with no result.

**Comment by andrei-blaj** [comment]
I'm not as familiar with SwiftUI as I am with Swift.
I've only used SwiftUI to build widgets, however I believe I've seen SwiftUI tutorials on YouTube on how to build the App Store and the transition. I think it's worth a try.

**Comment by Juhnkerg** [comment]
Yes, I am mainly having problems in UIScrollview and haven't found a proper way to judge and set bounce properties in swiftUI yet.
